/* Theme */
export const CHANGE_THEME = 'CHANGE_THEME';
/* Theme */

/* Auth */
export const GET_LOGIN_REQUEST = 'GET_LOGIN_REQUEST';
export const GET_LOGIN_SUCCESS = 'GET_LOGIN_SUCCESS';
export const GET_LOGIN_FAILURE = 'GET_LOGIN_FAILURE';

export const GET_CONTEXT_REQUEST = 'GET_CONTEXT_REQUEST';
export const GET_CONTEXT_SUCCESS = 'GET_CONTEXT_SUCCESS';
export const GET_CONTEXT_FAILURE = 'GET_CONTEXT_FAILURE';

export const FETCH_CONFIG_REQUEST = 'FETCH_CONFIG_REQUEST';
export const FETCH_CONFIG_SUCCESS = 'FETCH_CONFIG_SUCCESS';
export const FETCH_CONFIG_FAILURE = 'FETCH_CONFIG_FAILURE';

export const FETCH_INFORMATION_REQUEST = 'FETCH_INFORMATION_REQUEST';
export const FETCH_INFORMATION_SUCCESS = 'FETCH_INFORMATION_SUCCESS';
export const FETCH_INFORMATION_FAILURE = 'FETCH_INFORMATION_FAILURE';

export const FETCH_INFORMATION_ITEMS_REQUEST =
  'FETCH_INFORMATION_ITEMS_REQUEST';
export const FETCH_INFORMATION_ITEMS_SUCCESS =
  'FETCH_INFORMATION_ITEMS_SUCCESS';
export const FETCH_INFORMATION_ITEMS_FAILURE =
  'FETCH_INFORMATION_ITEMS_FAILURE';

export const FETCH_FAQS_REQUEST = 'FETCH_FAQS_REQUEST';
export const FETCH_FAQS_SUCCESS = 'FETCH_FAQS_SUCCESS';
export const FETCH_FAQS_FAILURE = 'FETCH_FAQS_FAILURE';

export const UPDATE_TASK_REQUEST = 'UPDATE_TASK_REQUEST';
export const UPDATE_TASK_SUCCESS = 'UPDATE_TASK_SUCCESS';
export const UPDATE_TASK_FAILURE = 'UPDATE_TASK_FAILURE';

export const ADD_FEEDBACK_REQUEST = 'ADD_FEEDBACK_REQUEST';
export const ADD_FEEDBACK_SUCCESS = 'ADD_FEEDBACK_SUCCESS';
export const ADD_FEEDBACK_FAILURE = 'ADD_FEEDBACK_FAILURE';

/* Dashboard */
export const NAVIGATION_CHANGE = 'NAVIGATION_CHANGED';
export const PIN_CALENDAR_CHANGE = 'PIN_CALENDAR_CHANGE';
export const SEARCH_KEY_CHANGE = 'SEARCH_KEY_CHANGE';
export const SEARCH_RESULT_CHANGE = 'SEARCH_RESULT_CHANGE';
export const FILTER_KEY_CHANGE = 'FILTER_KEY_CHANGE';
export const SEARCH_DIALOG_TRIGGER = 'SEARCH_DIALOG_TRIGGER';
export const CALENDAR_DIALOG_TRIGGER = 'CALENDAR_DIALOG_TRIGGER';
export const FAVORITE_DIALOG_TRIGGER = 'FAVORITE_DIALOG_TRIGGER';
export const LINKS_DIALOG_TRIGGER = 'LINKS_DIALOG_TRIGGER';
export const FEEDBACK_DIALOG_TRIGGER = 'FEEDBACK_DIALOG_TRIGGER';
export const WARNING_ACCEPT = 'WARNING_ACCEPT';
export const GET_FAVORITES = 'GET_FAVORITES';
/* Dashboard */
