/* Theme */
export const CHANGE_THEME = 'CHANGE_THEME';
/* Theme */

/* Auth */
export const GET_LOGIN_REQUEST = 'GET_LOGIN_REQUEST';
export const GET_LOGIN_SUCCESS = 'GET_LOGIN_SUCCESS';
export const GET_LOGIN_FAILURE = 'GET_LOGIN_FAILURE';

export const FETCH_AUTH_USER_GROUPS_REQUEST = 'FETCH_AUTH_USER_GROUPS_REQUEST';
export const FETCH_AUTH_USER_GROUPS_SUCCESS = 'FETCH_AUTH_USER_GROUPS_SUCCESS';
export const FETCH_AUTH_USER_GROUPS_FAILURE = 'FETCH_AUTH_USER_GROUPS_FAILURE';

export const GET_CONTEXT_REQUEST = 'GET_CONTEXT_REQUEST';
export const GET_CONTEXT_SUCCESS = 'GET_CONTEXT_SUCCESS';
export const GET_CONTEXT_FAILURE = 'GET_CONTEXT_FAILURE';

export const FETCH_CONFIG_REQUEST = 'FETCH_CONFIG_REQUEST';
export const FETCH_CONFIG_SUCCESS = 'FETCH_CONFIG_SUCCESS';
export const FETCH_CONFIG_FAILURE = 'FETCH_CONFIG_FAILURE';

export const FETCH_TASKS_REQUEST = 'FETCH_TASKS_REQUEST';
export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS';
export const FETCH_TASKS_FAILURE = 'FETCH_TASKS_FAILURE';

export const FETCH_INFORMATION_REQUEST = 'FETCH_INFORMATION_REQUEST';
export const FETCH_INFORMATION_SUCCESS = 'FETCH_INFORMATION_SUCCESS';
export const FETCH_INFORMATION_FAILURE = 'FETCH_INFORMATION_FAILURE';

export const FETCH_INFORMATION_ITEMS_REQUEST =
  'FETCH_INFORMATION_ITEMS_REQUEST';
export const FETCH_INFORMATION_ITEMS_SUCCESS =
  'FETCH_INFORMATION_ITEMS_SUCCESS';
export const FETCH_INFORMATION_ITEMS_FAILURE =
  'FETCH_INFORMATION_ITEMS_FAILURE';

export const FETCH_GROUPS_REQUEST = 'FETCH_GROUPS_REQUEST';
export const FETCH_GROUPS_SUCCESS = 'FETCH_GROUPS_SUCCESS';
export const FETCH_GROUPS_FAILURE = 'FETCH_GROUPS_FAILURE';

export const FETCH_TICKETS_REQUEST = 'FETCH_TICKETS_REQUEST';
export const FETCH_TICKETS_SUCCESS = 'FETCH_TICKETS_SUCCESS';
export const FETCH_TICKETS_FAILURE = 'FETCH_TICKETS_FAILURE';

export const FETCH_FAQS_REQUEST = 'FETCH_FAQS_REQUEST';
export const FETCH_FAQS_SUCCESS = 'FETCH_FAQS_SUCCESS';
export const FETCH_FAQS_FAILURE = 'FETCH_FAQS_FAILURE';

export const FETCH_LINKS_REQUEST = 'FETCH_LINKS_REQUEST';
export const FETCH_LINKS_SUCCESS = 'FETCH_LINKS_SUCCESS';
export const FETCH_LINKS_FAILURE = 'FETCH_LINKS_FAILURE';

export const UPDATE_TASK_REQUEST = 'UPDATE_TASK_REQUEST';
export const UPDATE_TASK_SUCCESS = 'UPDATE_TASK_SUCCESS';
export const UPDATE_TASK_FAILURE = 'UPDATE_TASK_FAILURE';

export const ADD_LINK_REQUEST = 'ADD_LINK_REQUEST';
export const ADD_LINK_SUCCESS = 'ADD_LINK_SUCCESS';
export const ADD_LINK_FAILURE = 'ADD_LINK_FAILURE';

export const ADD_FEEDBACK_REQUEST = 'ADD_FEEDBACK_REQUEST';
export const ADD_FEEDBACK_SUCCESS = 'ADD_FEEDBACK_SUCCESS';
export const ADD_FEEDBACK_FAILURE = 'ADD_FEEDBACK_FAILURE';

export const UPDATE_LINK_REQUEST = 'UPDATE_LINK_REQUEST';
export const UPDATE_LINK_SUCCESS = 'UPDATE_LINK_SUCCESS';
export const UPDATE_LINK_FAILURE = 'UPDATE_LINK_FAILURE';

export const DELETE_LINK_REQUEST = 'DELETE_LINK_REQUEST';
export const DELETE_LINK_SUCCESS = 'DELETE_LINK_SUCCESS';
export const DELETE_LINK_FAILURE = 'DELETE_LINK_FAILURE';

export const SET_MAPPED_GROUPS = 'SET_MAPPED_GROUPS';

export const SET_EXPANDED_GROUPS = 'SET_EXPANDED_GROUPS';
/* Auth */

/* People Picker */
export const FETCH_PEOPLEPICKER_USERS_REQUEST =
  'FETCH_PEOPLEPICKER_USERS_REQUEST';
export const FETCH_PEOPLEPICKER_USERS_SUCCESS =
  'FETCH_PEOPLEPICKER_USERS_SUCCESS';
export const FETCH_PEOPLEPICKER_USERS_FAILURE =
  'FETCH_PEOPLEPICKER_USERS_FAILURE';
/* People Picker */

/* Dashboard */
export const NAVIGATION_CHANGE = 'NAVIGATION_CHANGED';
export const PIN_CALENDAR_CHANGE = 'PIN_CALENDAR_CHANGE';
export const SEARCH_KEY_CHANGE = 'SEARCH_KEY_CHANGE';
export const SEARCH_RESULT_CHANGE = 'SEARCH_RESULT_CHANGE';
export const FILTER_KEY_CHANGE = 'FILTER_KEY_CHANGE';
export const SEARCH_DIALOG_TRIGGER = 'SEARCH_DIALOG_TRIGGER';
export const CALENDAR_DIALOG_TRIGGER = 'CALENDAR_DIALOG_TRIGGER';
export const FAVORITE_DIALOG_TRIGGER = 'FAVORITE_DIALOG_TRIGGER';
export const LINKS_DIALOG_TRIGGER = 'LINKS_DIALOG_TRIGGER';
export const FEEDBACK_DIALOG_TRIGGER = 'FEEDBACK_DIALOG_TRIGGER';
export const WARNING_ACCEPT = 'WARNING_ACCEPT';
export const GET_FAVORITES = 'GET_FAVORITES';
/* Dashboard */
