/* Theme */
export const CHANGE_THEME = 'CHANGE_THEME';
/* Theme */

/* Businesses */
export const LOAD_BUSINESSES_REQUEST = 'LOAD_BUSINESSES_REQUEST';
export const LOAD_BUSINESSES_SUCCESS = 'LOAD_BUSINESSES_SUCCESS';
export const LOAD_BUSINESSES_FAILURE = 'LOAD_BUSINESSES_FAILURE';

export const REGISTER_BUSINESS_REQUEST = 'REGISTER_BUSINESS_REQUEST';
export const REGISTER_BUSINESS_SUCCESS = 'REGISTER_BUSINESS_SUCCESS';
export const REGISTER_BUSINESS_FAILURE = 'REGISTER_BUSINESS_FAILURE';
/* Businesses */
